spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/weather_diary
    driver-class-name: org.mariadb.jdbc.Driver
    username: weather_user
    password: weather1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
